
                    WITH epoch_data AS (
                        SELECT 
                            epoch,
                            (SUM(leader_slots::numeric * activated_stake) / NULLIF(SUM(activated_stake::numeric), 0))::bigint AS avg_stake_weighted_leader_slots
                        FROM validator_stats
                        WHERE epoch = 752
                        GROUP BY epoch
                    ),
                    main_aggregates AS (
                        SELECT
                            AVG(commission) AS avg_commission,
                            AVG(epoch_credits) AS avg_credits,
                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY epoch_credits) AS median_credits,
                            SUM(cu)::numeric / NULLIF(SUM(blocks_produced), 0) AS avg_cu_per_block,
                            AVG(mev_commission) AS avg_mev_commission,
                            SUM(mev_earned)::numeric / NULLIF(SUM(blocks_produced), 0) AS avg_mev_per_block,
                            AVG(mev_to_validator) AS avg_mev_to_validator,
                            AVG(mev_to_jito_block_engine) AS avg_mev_to_jito_block_engine,
                            AVG(mev_to_jito_tip_router) AS avg_mev_to_jito_tip_router,
                            SUM(validator_priority_fees)::numeric / NULLIF(SUM(blocks_produced), 0) AS avg_priority_fees_per_block,
                            SUM(rewards)::numeric / NULLIF(SUM(blocks_produced), 0) AS avg_rewards_per_block,
                            SUM(validator_signature_fees)::numeric / NULLIF(SUM(blocks_produced), 0) AS avg_signature_fees_per_block,
                            SUM(user_tx_included_in_blocks)::numeric / NULLIF(SUM(blocks_produced), 0) AS avg_user_tx_per_block,
                            SUM(vote_cost)::numeric / NULLIF(SUM(blocks_produced), 0) AS avg_vote_cost_per_block,
                            SUM(vote_tx_included_in_blocks)::numeric / NULLIF(SUM(blocks_produced), 0) AS avg_vote_tx_per_block,
                            SUM(tx_included_in_blocks)::numeric / NULLIF(SUM(blocks_produced), 0) AS avg_tx_per_block,
                            AVG(votes_cast)::numeric AS avg_votes_cast,
                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY CASE WHEN blocks_produced > 0 THEN rewards::numeric / blocks_produced ELSE NULL END) AS median_rewards_per_block,
                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY CASE WHEN blocks_produced > 0 THEN mev_earned::numeric / blocks_produced ELSE NULL END) AS median_mev_per_block,
                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY CASE WHEN blocks_produced > 0 THEN mev_to_jito_block_engine::numeric / blocks_produced ELSE NULL END) AS median_mev_to_jito_block_engine,
                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY CASE WHEN blocks_produced > 0 THEN mev_to_jito_tip_router::numeric / blocks_produced ELSE NULL END) AS median_mev_to_jito_tip_router,
                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY votes_cast) AS median_votes_cast,
                            SUM(activated_stake) AS total_active_stake,
                            SUM(blocks_produced) AS total_blocks_produced,
                            SUM(epoch_credits) AS total_credits,
                            SUM(cu) AS total_cu,
                            SUM(mev_earned) AS total_mev_earned,
                            SUM(mev_earned * mev_commission / 10000) AS total_mev_to_validator,
                            SUM(CASE 
                                WHEN epoch < 752 THEN mev_earned / 0.95  -- Includes 751
                                WHEN epoch > 751 THEN mev_earned / 0.97
                                ELSE NULL
                            END) AS total_mev_to_jito_block_engine,
                            SUM(CASE
                                WHEN epoch > 751 THEN mev_earned / 0.97  -- Excludes 751
                                ELSE NULL
                            END) AS total_mev_to_jito_tip_router,
                            SUM(signatures) AS total_signatures,
                            SUM(tx_included_in_blocks) AS total_tx,
                            SUM(user_tx_included_in_blocks) AS total_user_tx,
                            SUM(total_block_rewards_after_burn) AS total_validator_fees,
                            SUM(validator_priority_fees) AS total_validator_priority_fees,
                            SUM(validator_signature_fees) AS total_validator_signature_fees,
                            SUM(vote_cost) AS total_vote_cost,
                            SUM(vote_tx_included_in_blocks) AS total_vote_tx,
                            SUM(votes_cast) AS total_votes_cast,
                            SUM(skip_rate * activated_stake) / NULLIF(SUM(activated_stake), 0) AS avg_stake_weighted_skip_rate,
                            AVG(CASE 
                                WHEN activated_stake > 0 AND leader_slots > 0 
                                THEN (activated_stake::float / 1000000000) / (leader_slots::float / 4) 
                                ELSE NULL 
                            END) AS average_sol_per_4_slots,
                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY 
                                CASE 
                                    WHEN activated_stake > 0 AND leader_slots > 0 
                                    THEN (activated_stake::float / 1000000000) / (leader_slots::float / 4) 
                                    ELSE NULL 
                                END
                            ) AS median_sol_per_4_slots,
                            AVG(activated_stake)::numeric AS avg_active_stake,
                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY activated_stake) AS median_active_stake 
                        FROM validator_stats vs
                        WHERE vs.epoch = 752
                    ),
                    slot_time_stats AS (
                        SELECT
                            MIN(block_slot) AS min_slot,
                            MAX(block_slot) AS max_slot,
                            MIN(block_time) AS min_block_time,
                            MAX(block_time) AS max_block_time
                        FROM validator_data
                        WHERE epoch = 752
                    ),
                    epoch_slot_info AS (
                        SELECT
                            752 * 432000 AS epoch_start_slot,
                            (752 + 1) * 432000 - 1 AS epoch_end_slot
                    )
                    INSERT INTO epoch_aggregate_data (
                        avg_commission,
                        avg_credits,
                        median_credits,
                        avg_cu_per_block,
                        avg_mev_commission,
                        avg_mev_per_block,
                        avg_mev_to_validator,
                        avg_mev_to_jito_block_engine,
                        avg_mev_to_jito_tip_router,
                        avg_priority_fees_per_block,
                        avg_rewards_per_block,
                        avg_signature_fees_per_block,
                        avg_stake_weighted_skip_rate,
                        avg_stake_weighted_leader_slots,
                        avg_user_tx_per_block,
                        avg_vote_cost_per_block,
                        avg_vote_tx_per_block,
                        avg_tx_per_block, 
                        avg_votes_cast,
                        epoch,
                        epoch_start_slot,
                        epoch_end_slot,
                        median_rewards_per_block,
                        median_mev_per_block,
                        median_mev_to_jito_block_engine,
                        median_mev_to_jito_tip_router,
                        median_votes_cast,
                        total_active_stake,
                        total_blocks_produced,
                        total_credits,
                        total_cu,
                        total_mev_earned,
                        total_mev_to_validator,
                        total_mev_to_jito_block_engine,
                        total_mev_to_jito_tip_router,
                        total_signatures,
                        total_tx,
                        total_user_tx,
                        total_validator_fees,
                        total_validator_priority_fees,
                        total_validator_signature_fees,
                        total_vote_cost,
                        total_vote_tx,
                        total_votes_cast,
                        min_slot,
                        max_slot,
                        min_block_time,
                        max_block_time,
                        average_sol_per_4_slots,
                        median_sol_per_4_slots,
                        avg_active_stake,
                        median_active_stake
                    )
                    SELECT
                        ma.avg_commission,
                        ma.avg_credits,
                        ma.median_credits,
                        ma.avg_cu_per_block,
                        ma.avg_mev_commission,
                        ma.avg_mev_per_block,
                        ma.avg_mev_to_validator,
                        ma.avg_mev_to_jito_block_engine,
                        ma.avg_mev_to_jito_tip_router,
                        ma.avg_priority_fees_per_block,
                        ma.avg_rewards_per_block,
                        ma.avg_signature_fees_per_block,
                        ma.avg_stake_weighted_skip_rate,
                        ed.avg_stake_weighted_leader_slots,
                        ma.avg_user_tx_per_block,
                        ma.avg_vote_cost_per_block,
                        ma.avg_vote_tx_per_block,
                        ma.avg_tx_per_block,
                        ma.avg_votes_cast,
                        752 AS epoch,
                        esi.epoch_start_slot,
                        esi.epoch_end_slot,
                        ma.median_rewards_per_block,
                        ma.median_mev_per_block,
                        ma.median_mev_to_jito_block_engine,
                        ma.median_mev_to_jito_tip_router,
                        ma.median_votes_cast,
                        ma.total_active_stake,
                        ma.total_blocks_produced,
                        ma.total_credits,
                        ma.total_cu,
                        ma.total_mev_earned,
                        ma.total_mev_to_validator,
                        ma.total_mev_to_jito_block_engine,
                        ma.total_mev_to_jito_tip_router,
                        ma.total_signatures,
                        ma.total_tx,
                        ma.total_user_tx,
                        ma.total_validator_fees,
                        ma.total_validator_priority_fees,
                        ma.total_validator_signature_fees,
                        ma.total_vote_cost,
                        ma.total_vote_tx,
                        ma.total_votes_cast,
                        sts.min_slot,
                        sts.max_slot,
                        sts.min_block_time,
                        sts.max_block_time,
                        ma.average_sol_per_4_slots,
                        ma.median_sol_per_4_slots,
                        ma.avg_active_stake,
                        ma.median_active_stake
                    FROM
                        main_aggregates ma,
                        slot_time_stats sts,
                        epoch_slot_info esi,
                        epoch_data ed
                    ON CONFLICT (epoch) DO UPDATE SET
                        avg_commission = EXCLUDED.avg_commission,
                        avg_credits = EXCLUDED.avg_credits,
                        median_credits = EXCLUDED.median_credits,
                        avg_cu_per_block = EXCLUDED.avg_cu_per_block,
                        avg_mev_commission = EXCLUDED.avg_mev_commission,
                        avg_mev_per_block = EXCLUDED.avg_mev_per_block,
                        avg_mev_to_validator = EXCLUDED.avg_mev_to_validator,
                        avg_mev_to_jito_block_engine = EXCLUDED.avg_mev_to_jito_block_engine,
                        avg_mev_to_jito_tip_router = EXCLUDED.avg_mev_to_jito_tip_router,
                        avg_priority_fees_per_block = EXCLUDED.avg_priority_fees_per_block,
                        avg_rewards_per_block = EXCLUDED.avg_rewards_per_block,
                        avg_signature_fees_per_block = EXCLUDED.avg_signature_fees_per_block,
                        avg_stake_weighted_skip_rate = EXCLUDED.avg_stake_weighted_skip_rate,
                        avg_stake_weighted_leader_slots = EXCLUDED.avg_stake_weighted_leader_slots,
                        avg_user_tx_per_block = EXCLUDED.avg_user_tx_per_block,
                        avg_vote_cost_per_block = EXCLUDED.avg_vote_cost_per_block,
                        avg_vote_tx_per_block = EXCLUDED.avg_vote_tx_per_block,
                        avg_votes_cast = EXCLUDED.avg_votes_cast,
                        avg_tx_per_block = EXCLUDED.avg_tx_per_block,
                        median_rewards_per_block = EXCLUDED.median_rewards_per_block,
                        median_mev_per_block = EXCLUDED.median_mev_per_block,
                        median_mev_to_jito_block_engine = EXCLUDED.median_mev_to_jito_block_engine,
                        median_mev_to_jito_tip_router = EXCLUDED.median_mev_to_jito_tip_router,
                        median_votes_cast = EXCLUDED.median_votes_cast,
                        total_active_stake = EXCLUDED.total_active_stake,
                        total_blocks_produced = EXCLUDED.total_blocks_produced,
                        total_credits = EXCLUDED.total_credits,
                        total_cu = EXCLUDED.total_cu,
                        total_mev_earned = EXCLUDED.total_mev_earned,
                        total_mev_to_validator = EXCLUDED.total_mev_to_validator,
                        total_mev_to_jito_block_engine = EXCLUDED.total_mev_to_jito_block_engine,
                        total_mev_to_jito_tip_router = EXCLUDED.total_mev_to_jito_tip_router,
                        total_signatures = EXCLUDED.total_signatures,
                        total_tx = EXCLUDED.total_tx,
                        total_user_tx = EXCLUDED.total_user_tx,
                        total_validator_fees = EXCLUDED.total_validator_fees,
                        total_validator_priority_fees = EXCLUDED.total_validator_priority_fees,
                        total_validator_signature_fees = EXCLUDED.total_validator_signature_fees,
                        total_vote_cost = EXCLUDED.total_vote_cost,
                        total_vote_tx = EXCLUDED.total_vote_tx,
                        total_votes_cast = EXCLUDED.total_votes_cast,
                        epoch_start_slot = EXCLUDED.epoch_start_slot,
                        epoch_end_slot = EXCLUDED.epoch_end_slot,
                        min_slot = EXCLUDED.min_slot,
                        max_slot = EXCLUDED.max_slot,
                        min_block_time = EXCLUDED.min_block_time,
                        max_block_time = EXCLUDED.max_block_time,
                        average_sol_per_4_slots = EXCLUDED.average_sol_per_4_slots,
                        median_sol_per_4_slots = EXCLUDED.median_sol_per_4_slots,
                        avg_active_stake = EXCLUDED.avg_active_stake,
                        median_active_stake = EXCLUDED.median_active_stake;
                