CREATE TABLE IF NOT EXISTS xshin_data (
    epoch INTEGER NOT NULL,
    vote_account_pubkey VARCHAR(44) NOT NULL,
    total_score DOUBLE PRECISION,
    name VARCHAR(100),
    icon_url TEXT,
    details TEXT,
    website_url TEXT,
    city VARCHAR(100),
    country CHAR(2),
    stake_active BIGINT,
    stake_activating BIGINT,
    stake_deactivating BIGINT,
    target_pool_stake BIGINT,
    raw_score_skip_rate DOUBLE PRECISION,
    raw_score_prior_skip_rate DOUBLE PRECISION,
    raw_score_subsequent_skip_rate DOUBLE PRECISION,
    raw_score_cu DOUBLE PRECISION,
    raw_score_latency DOUBLE PRECISION,
    raw_score_llv DOUBLE PRECISION,
    raw_score_cv DOUBLE PRECISION,
    raw_score_vote_inclusion DOUBLE PRECISION,
    raw_score_apy DOUBLE PRECISION,
    raw_score_pool_extra_lamports DOUBLE PRECISION,
    raw_score_city_concentration DOUBLE PRECISION,
    raw_score_country_concentration DOUBLE PRECISION,
    normalized_score_skip_rate DOUBLE PRECISION,
    normalized_score_prior_skip_rate DOUBLE PRECISION,
    normalized_score_subsequent_skip_rate DOUBLE PRECISION,
    normalized_score_cu DOUBLE PRECISION,
    normalized_score_latency DOUBLE PRECISION,
    normalized_score_llv DOUBLE PRECISION,
    normalized_score_cv DOUBLE PRECISION,
    normalized_score_vote_inclusion DOUBLE PRECISION,
    normalized_score_apy DOUBLE PRECISION,
    normalized_score_pool_extra_lamports DOUBLE PRECISION,
    normalized_score_city_concentration DOUBLE PRECISION,
    normalized_score_country_concentration DOUBLE PRECISION,
    pool_stake_active BIGINT,
    pool_stake_activating BIGINT,
    pool_stake_deactivating BIGINT,
    noneligibility_reasons JSONB,
    PRIMARY KEY (epoch, vote_account_pubkey)
);